version: '3.8'
services:
  bot:
    container_name: garmin-live-track-bot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    restart: always
    command: npm run start:prod
    env_file: .env
    network_mode: bridge
