version: '3.8'
services:
  bot:
    container_name: garmin-live-track-bot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7000:5000
    restart: always
    env_file:
      - stack.env
    command: npm run start:prod
    network_mode: bridge
